---
apiVersion: v1
kind: Service
metadata:
  name: trading
  labels:
    app: trading
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: trading
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
  labels:
    app: trading
spec:
  selector:
    matchLabels:
      app: trading
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trading
        tier: backend
    spec:
      containers:
        - name: trading-app-dev
          image: ccalvinnguyen/trading-app
          env:
            - name: PSQL_HOST
              value: trading-psql
            - name: PSQL_PORT
              value: "5432"
            - name: PSQL_DB
              value: jrvstrading
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: psql-info
                  key: user
            - name: PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-info
                  key: password
            - name: IEX_PUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: trading-app
                  key: IEX_PUB_TOKEN
          ports:
            - containerPort: 8080
              name: trading